name: Deploy Application

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create .env File
        run: |
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" > .env

      - name: Load and Partially Print API Key (Last 4 Characters)
        run: |
          source .env  # Load environment variables
          echo "API Key Loaded: ****${GEMINI_API_KEY: -4}"  
          # Mask all but the last 4 characters
